version: '3'

services:
  attraksjoner-server:
    build: .cloud/docker
    image: attraksjoner-serverimg
    restart: unless-stopped
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached
      - ".cloud/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
    networks:
      - default

  web:
    image: nginx:stable-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=attrak.tusenfryd.no
      - LETSENCRYPT_HOST=attrak.tusenfryd.no
      - LETSENCRYPT_EMAIL=eirik@tusenfryd.no
    volumes:
      - .cloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - attraksjoner-server
    networks:
      - default

  mysql:
    container_name: attrak-database
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=OJn*!G=3PxXnU,R
      - MYSQL_DATABASE=attraksjoner
    volumes:
      - db-data-attrak:/var/lib/mysql
    networks:
      - default

volumes:
  db-data-attrak:

networks:
  default:
    external:
      name: hittegodsv2_app-network
